# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Test with pytest
      run: |
        pytest -v --junitxml=test-reports/report.xml --html=test-reports/report.html
      env:
        SELENIUM_DRIVER_KIND: remote
        WINDOW_RESOLUTION : DESKTOP_1920X1080
        BASE_URL : https://yandex.ru
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      if: always()

      with:
        name: test-reports
        path: test-reports

    services:
      headless:
        image: browserless/chrome:latest
        ports:
          - 3000:3000